// <auto-generated />
namespace HomeBudgetManagement.Domain
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FileColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202012150413372_FileColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
