// <auto-generated />
namespace HomeBudgetManagement.Domain
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddIncome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIncome));
        
        string IMigrationMetadata.Id
        {
            get { return "202101190728305_Income"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
