// <auto-generated />
namespace HomeBudgetManagement.Domain
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Accounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Accounts));
        
        string IMigrationMetadata.Id
        {
            get { return "202101300350289_Account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
